language: node_js
node_js: stable



branches:
  only:
  - blog-source



# # 配置环境
# before_install:
# # 替换为刚才生成的解密信息
# -before_install:
# - openssl aes-256-cbc -K $encrypted_e8b9f665f844_key -iv $encrypted_e8b9f665f844_iv
#   -in ssh.enc -out ssh -d

# # 改变文件权限
# - chmod 600 ~/.ssh/id_rsa 
# # 配置 ssh
# - eval $(ssh-agent)
# - ssh-add ~/.ssh/id_rsa
# - cp .travis/ssh_config ~/.ssh/config
# 配置 git 替换为自己的信息
# - git config --global user.name 'kentsx'
# - git config --global user.email kentisxie@126.com


# S: Build Lifecycle
install:
  - npm install

# 缓存文件
cache:
  directories:
    - node_modules

#before_script:
 # - npm install -g gulp

script:
  # - npm run deploy
  - cross-env YUQUE_TOKEN=$YUQUE_TOKEN
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "kentsx"
  - git config user.email "kentisxie@126.com"
  - git add .
  - git commit -m " @$TRAVIS_BUILD_NUMBER@TravisCI - `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

# branches:
#   only:
#     - blog-source
env:
 global:
   - GH_REF: github.com/kentsx/blog.git

